INSERT INTO brand (name, designer) VALUES ('Gap', 'Dorothea Goodinge');
INSERT INTO brand (name, designer) VALUES ('Banana Republic', 'Theodore Lafayette Watermelon');
INSERT INTO brand (name, designer) VALUES ('Old Navy', 'Alexandra Hamilton');
INSERT INTO brand (name, designer) VALUES ('Athleta', 'Chris Hemsworth');
INSERT INTO brand (name, designer) VALUES ('Intermix', 'Laura Michele');
INSERT INTO brand (name, designer) VALUES ('Database Chique', 'Scott Johnson');
INSERT INTO brand (name, designer) VALUES ('SQL Supreme', 'Scott Johnson');
INSERT INTO brand (name, designer) VALUES ('No Sql no worries', 'Scott Johnson');
INSERT INTO brand (name, designer) VALUES ('Bropadslick', 'Jeremy Brown');
INSERT INTO brand (name, designer) VALUES ('Way Weddington', 'Drew Fancy');