INSERT INTO `brand` (`name`, `designer`) VALUES ("Champlin, Jaskolski and Klocko","Dorothea Goodinge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kautzer, Maggio and Erdman","Galen Wykey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Christiansen Inc","Benoite Goding");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cormier-Kunze","Kent Koppen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Buckridge-Schiller","Sallyanne Radoux");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cronin-Kuhic","Vivian Strothers");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Corwin Group","Karalee Karys");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lynch, Keebler and Harris","Oona Hundley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grady, Oberbrunner and Jast","Isa Pilmoor");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weber, Kunze and Mertz","Willetta Hembry");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Zemlak Group","Geraldine Burgoin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hane, Brown and Bashirian","Fairleigh Salt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("D'Amore-Hodkiewicz","Nichole Struthers");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Howell, Sipes and Stroman","Averil Carles");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Toy LLC","Pat Seilmann");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Leuschke, Brakus and Miller","Aguie de Werk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lubowitz and Sons","Donnajean Clew");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walker Inc","Rosalind Timmins");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Koelpin LLC","Karlis Sictornes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kerluke-Bosco","Wendye Silley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schiller Group","Gianna Guido");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Keeling-Klocko","Hartwell Loughman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walsh-Dickens","Star Corkett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("D'Amore Inc","Ursulina Bruno");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wiegand, Robel and Roob","Vikki Berriball");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Barrows-Schowalter","Winni Callen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Douglas-Kirlin","Michal Cayette");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Blick Inc","Toni Sheron");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fritsch, Hudson and Graham","Berke Dufall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mitchell, Greenholt and O'Reilly","Honoria Godbolt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gusikowski Inc","Joey Balffye");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuhlman, Leuschke and Schaefer","Son Mulkerrins");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Sawayn-Rempel","Felix Cousens");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Auer, Schultz and Kuvalis","Vassili Zannini");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Thompson LLC","Delbert Lark");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Barton Inc","Hobey Jaquet");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brekke, Shanahan and Hermann","Valentina Bazely");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schiller, Harvey and D'Amore","Ginnifer Coleby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hettinger-Aufderhar","Benedicto Fawson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schoen-Pfeffer","Marget Schubuser");
INSERT INTO `brand` (`name`, `designer`) VALUES ("DuBuque-Zulauf","Ole McGragh");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Corwin, Beier and Ebert","Kristyn Couth");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stoltenberg, Donnelly and Daugherty","Seymour Seymour");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Legros, Goodwin and Gibson","Fonsie Black");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cronin and Sons","Yul Petru");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ruecker-Larkin","Trude Emerton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Okuneva-Bergnaum","Charlton Ellwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schmitt, Lubowitz and Schroeder","Drusi Fitton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mayert Inc","Devonna Carlon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hilpert Group","Ximenez Gingell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ziemann Group","Selinda Redwood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein Group","Tripp Oats");
INSERT INTO `brand` (`name`, `designer`) VALUES ("VonRueden LLC","Faith Reeson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bauch LLC","Shannen Akid");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Muller Group","Darcy Stelljes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Armstrong, Nicolas and Walter","Natale Jane");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mohr and Sons","Stacia Hand");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Denesik and Sons","Casey Allsworth");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Durgan, Haley and Hilll","Robin Jerams");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Greenfelder, Jenkins and Bogisich","Benny Nerney");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Batz-Prosacco","Freeman Highton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nicolas, Veum and Rowe","Elvera Pietz");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stark, Klocko and Nolan","Birgitta Kibard");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weber-Grant","Adelina Jeans");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Moen, Dare and Swaniawski","Lorianna Twidle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stehr Group","Carole Erridge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kertzmann LLC","Nell Wynch");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Windler LLC","Gabie Godbehere");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gerhold-Murray","Marissa Collens");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marks and Sons","Koenraad MacHoste");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wiegand Group","Alair Djuricic");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartoletti Group","Alyce Kreuzer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Anderson, Zboncak and Kassulke","Marita Henrys");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Graham-Kirlin","Clotilda Berkely");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Boyer, Boehm and Schuppe","Sandie Matresse");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rice, Schamberger and Weissnat","Janna Tremayle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stroman-Yundt","Candide Wyburn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Barton-Crooks","Diana Halbeard");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gottlieb Inc","Rianon Goosey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kemmer Group","Val Petigrew");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gislason, Ortiz and Dickens","Gaye Grestye");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bogisich Inc","Nickie Dorrian");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conn-Kirlin","Ray Ivanchov");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Watsica and Sons","Francyne Crawshaw");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuvalis and Sons","Wandie Mirralls");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Upton Group","Fraze Mansour");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pollich LLC","Luther Booley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Thompson, Stokes and Paucek","Chaunce Swafford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weissnat Group","Walker Paffot");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schimmel, Wolff and Leuschke","Shirline Mordin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mueller LLC","Anita Dealy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Auer, Hintz and Klein","Reed Dobsons");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bogisich, Russel and Bruen","Gery Cordle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("D'Amore, Sanford and Schroeder","Wanids Rao");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuhlman-Tremblay","Stormy Brokenshaw");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Towne, D'Amore and MacGyver","Andy Weeke");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kassulke Inc","Arabela Isakovitch");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gutkowski, Bogisich and Cremin","Abraham Larchiere");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ritchie and Sons","Korrie Cisar");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Turcotte, Dare and Walter","Cherida Biddlestone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Davis, Borer and Cummings","Rooney Askaw");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Turner and Sons","Kyle Fetherstonhaugh");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Powlowski LLC","Bradney Eilles");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wintheiser, Keeling and Orn","Wylma Leyes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johnston Group","Constancia Pering");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Breitenberg Inc","Gertrude Hamilton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Konopelski Inc","Barry Sibun");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Crooks Inc","Kevyn Dudny");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Farrell, Lesch and Grimes","Rube Telezhkin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hoeger Inc","Anissa Dewett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Predovic, Ankunding and Gislason","Emmery Curnock");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wyman, Walsh and O'Kon","Ursuline Tindley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dooley, Buckridge and Ullrich","Elbertina Crookston");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mohr-Schumm","Meriel Gloyens");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wisoky, Purdy and Huels","Mannie Weatherhogg");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Friesen Inc","Nalani Brambill");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weimann, Schroeder and Schmidt","Zollie Wiffen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reichert Group","Cecelia Tieman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Upton-Hilpert","Ursola McDermot");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bergnaum-Funk","Seana Siene");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johnson, Herzog and Pacocha","Muriel Luchetti");
INSERT INTO `brand` (`name`, `designer`) VALUES ("MacGyver Inc","Fanchette Forst");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kunze Inc","Kristoforo Chaulk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Murray Inc","Craig Heighton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marquardt, Murphy and Thiel","Duff McIlvenny");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Buckridge and Sons","Sephira Marzelli");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Parisian LLC","Latashia Hindsberg");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bernier-Marks","Joana Wahncke");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gibson, Marks and Gulgowski","Juliana Thackham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hammes, Hegmann and Weimann","Aggie Gallemore");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fadel and Sons","Licha Standingford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Herman and Sons","Gabbey Sanz");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Swaniawski, Mohr and McKenzie","Baxy Ruoff");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Prohaska, Ruecker and Bradtke","Hetty Goldspink");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Harber-Kuhlman","Peri Brehault");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Macejkovic-Williamson","Brooks Franzini");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bode LLC","Zulema Gloves");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jacobi, Jerde and Abshire","Alan Brophy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Simonis-Fisher","Artemas Bryde");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Haley, Gislason and Bins","Bess Caplan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lueilwitz, Bauch and Weissnat","Donnie Jellico");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Macejkovic, Oberbrunner and McCullough","Kimmi Lamacraft");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wilkinson, Wolff and Price","Phineas Berling");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Medhurst, Rolfson and Mills","Haleigh Philliphs");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Zemlak-Vandervort","Feliks Snell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stracke Group","Hannie De Vile");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ferry, McKenzie and Trantow","Nero Libreros");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Spencer, Cremin and Kunze","Reagen Hawket");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mueller LLC","Eustacia Ayrs");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wolff Group","Claus Vass");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dickens Group","Tabbi Chatenier");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hauck and Sons","Saloma Trazzi");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuphal-Grady","Juliette Odams");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lebsack, O'Reilly and Kirlin","Gail Grayham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Simonis Group","Ogdan Ellams");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Witting Group","Bartel Vyel");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hagenes, Daniel and Ondricka","Brett Cawley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein-Kreiger","Latia Teml");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stehr-Eichmann","Moria Duligall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cummerata, Considine and Wisoky","Ninette Koppeck");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Spinka-Williamson","Karyn Scollan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Morar-Towne","Janette Dummer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gerhold, Ankunding and Sauer","Selia Conry");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Huel-Conn","Constancy Coulston");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Abernathy Group","Bertrando Minnis");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rolfson-Raynor","Elita Coonihan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grady LLC","Fay Bolf");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hermiston, Jakubowski and Thompson","Sara Schlagh");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Harris LLC","Eryn O' Donohoe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartoletti Group","Andria Stellino");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Crona Group","Prudi Birden");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jast, Sporer and Murazik","Gordie Edwin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Witting-Schaefer","Waldemar Rene");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brown-Wilkinson","Dyna Exelby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brekke, Kling and Mueller","Howie Veronique");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Abshire-Satterfield","Nickolai Sully");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heaney-Bernhard","Erasmus Reddel");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Turcotte-Harris","Franni Olyet");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heathcote, Shields and Towne","Hercules Thorley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Considine, Bergstrom and McKenzie","Stephani Hambatch");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kshlerin-Blanda","Ibbie Keeler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kunde Group","Sarina Kinglesyd");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rohan-Gleason","Jody Pepys");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ankunding LLC","Silvio Plowman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hermiston, Rogahn and Ziemann","Gamaliel Hutcheson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Steuber, Boyer and Schuster","Myrvyn Josovich");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lang Inc","Hort Keatley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schmeler-Armstrong","Andrej Peacock");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Runte, Hessel and Wilkinson","Dallon Mix");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Carroll, Stehr and Eichmann","Dita Zotto");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Roberts-Sanford","Steffane Wallicker");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Kon Group","Hillard Butts");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McGlynn Group","Gorden Porritt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hoppe, Rohan and Stamm","Cairistiona Beche");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Goodwin LLC","Beatrisa Bernt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Collins Inc","Ilysa Nelligan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marvin, Bechtelar and Collins","Guss Botterman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Macejkovic Inc","Russell Srawley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Yost, Kunze and Halvorson","Glennie Tomaszewicz");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Harris LLC","Deloria Francombe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kunze, Wisoky and Quigley","Adele Danne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Feest-Hermann","Rochester Shirland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hamill, Cormier and Gutmann","Julianna Greeno");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mann, Yost and Wyman","Geraldine Christophle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weimann Inc","Ethe Bloss");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Baumbach-Jerde","Sergei Aronstein");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beatty, Ebert and Gusikowski","Dotty McRonald");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Crist, Buckridge and Corwin","Ferdinanda Crowder");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Runolfsdottir-Greenholt","Hamid Clapham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Blanda-Goldner","Fenelia Pochin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rippin-Welch","Katee Pearde");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bernhard and Sons","Lorant Cahani");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McKenzie, MacGyver and Gutkowski","Ediva Barukh");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jast LLC","Janine Vowles");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ferry-Ziemann","Kimmie Switzer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Sanford, Herman and Anderson","Leshia Bonar");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McCullough and Sons","Kamillah Sisey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tillman-Toy","Hadlee Pigrome");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kreiger-Kunze","Gabbey Couche");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weissnat-Lockman","Dillie McClinton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gottlieb-Pouros","Ned MacCague");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mraz, Bruen and Baumbach","Les Orred");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hodkiewicz, Corkery and Koepp","Rurik Joel");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Denesik-Tromp","Briana Cordingley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kshlerin Inc","Joelly Inwood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bailey Inc","Godwin Mackrell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schroeder-Cummerata","Murray Roomes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Konopelski-Bauch","Porter Orrom");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kub Inc","Sayres Androsik");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gaylord, Shields and Bechtelar","Melina Juggings");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Keebler, Ward and Windler","Delaney Andrioni");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hills Group","Andres Kits");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hoppe-Morar","Roda Balasini");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Zieme Group","Sharline Lucia");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jerde, Ferry and Schaden","Jarib Usher");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gorczany, Rosenbaum and Beer","Arden Edgecombe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dare, Windler and Zemlak","Philly Farlane");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ferry LLC","Beatrisa Bubbins");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schmidt-Walker","Jordana Stainson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hoeger-Goodwin","Conant Eslemont");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wiegand, Parker and Fahey","Rodrigo Chung");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Spencer, Stanton and Hagenes","Pasquale Gurge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schuster, Brakus and Reichert","Gabriell Flintiff");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Labadie, Renner and Frami","Bibby Dove");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bogan Group","Martynne Imloch");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conroy-Goyette","Jojo Sleight");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stehr-Zemlak","Karlan Leedal");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hand, Willms and Koepp","Ianthe Glayzer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Torp and Sons","Maisie Del Castello");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hegmann, Kuphal and Cummings","Lisha Thurston");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cummerata, Swift and Walsh","Kerry Elham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fritsch Inc","Vaughan Paeckmeyer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rowe-Cremin","Gilligan Tome");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hoppe LLC","Osmund MacAree");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Huels Inc","Curt Dron");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brekke-Glover","Ninetta Wybourne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stanton Inc","Kerrill Happs");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Crona Group","Esmeralda Smickle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ryan Inc","Guillema Baudet");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Becker-Beer","Olivier Stoving");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stiedemann and Sons","Westbrooke Pentony");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Howe, Parker and Miller","Isis Peterson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weber, Wisozk and Okuneva","Tomaso Marmyon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marvin-Kautzer","Anneliese Szymanzyk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jenkins Group","Janka Hedworth");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hoppe-Botsford","Aryn Liddon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Crist, Corkery and Mitchell","Che Munnings");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gulgowski Inc","Veronika Vero");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nikolaus LLC","Doll Braam");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rohan, Grady and Russel","Deeann Dible");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dietrich-Schimmel","Nancie Hadigate");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kub and Sons","Stephenie Phizacklea");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stehr, Russel and Macejkovic","Hyacinth Handyside");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brakus-Kreiger","Taddeo Firbanks");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stiedemann, Hamill and Rodriguez","Tierney Hartin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Feeney and Sons","Brant Westhofer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Davis Inc","Davine Gumm");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pfannerstill Inc","Roanna Antonetti");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hessel, Hudson and Bartell","Julissa Verrall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dicki, Homenick and Gaylord","Ed Burk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Becker-Kuvalis","Bernadene Gowanlock");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Barton and Sons","Ardelle Ness");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bednar, Hane and Hansen","Andrew Egar");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Sipes, Kuhn and Schneider","Alvera Coveley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hintz-Christiansen","Lucila Grebner");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kovacek LLC","Lynette O'Bruen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Considine LLC","Blanche Wakerley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pfeffer, Larson and Larkin","Anallise Swinney");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Prohaska, Hermiston and Purdy","Karmen Barnaby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Barton Inc","Carley Yule");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Connell-Schowalter","Reeba Tomaszczyk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Miller, Weimann and Reichel","Kelley Gearing");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Steuber, Koelpin and Langosh","Westleigh Bampfield");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Breitenberg-Grimes","Chiquia Robathon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grady-Wilkinson","Gnni Eyes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hand-Gusikowski","Karylin Mullin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wehner Group","Barbey Tinkler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cremin LLC","Peter Whitwam");
INSERT INTO `brand` (`name`, `designer`) VALUES ("D'Amore Group","Northrup Calltone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Smith-Corwin","Marsh Reddan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Daniel, Hansen and Smith","Goraud Wilcinskis");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lebsack-Hauck","Cornie Jeggo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Kon-Boyer","Martin Naul");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Keefe and Sons","Lanette Redihough");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Greenholt, Wilkinson and Kirlin","Jacquie Cannell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jerde, Kulas and Schuppe","Elianore Gonzalo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Sipes, Collier and Hand","Fiann Olohan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beer-Renner","Malva Roden");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dickinson-Keebler","Anjela Duinkerk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Waters LLC","Chrotoem Kleimt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Herman, Nolan and Wolff","Pascale Imason");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jerde, Nicolas and Hamill","Toni McCalum");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bergnaum LLC","Harrie Rysom");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cronin, Mitchell and Cruickshank","Manda Fosberry");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gaylord, Goodwin and Langworth","Leta Breckin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marquardt, Deckow and Wolff","Cesare Saltrese");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Zemlak Group","Hatty Coombes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Treutel, Johnston and Mitchell","Hobie Prangnell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hirthe-Koss","Currie Guilaem");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hermann-Zulauf","Damian Doveston");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Funk, Mohr and Streich","Karlan Rubin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Breitenberg, Strosin and Nienow","Thadeus Cullerne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rodriguez LLC","Legra Ciccotto");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Okuneva, Gleichner and Vandervort","Ravi Smitherham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Macejkovic-Rohan","Jobi Battabee");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pouros-Hoppe","Stacey Ciraldo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Boyer LLC","Salomi Bartlosz");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ruecker, Haag and Wisoky","Ursa Stonhewer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beier and Sons","Walker Dellenbach");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bergstrom-Maggio","Gabriel Laxon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mertz and Sons","Yard Whewill");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fisher, Russel and Wehner","Elisha Sollam");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hills-Gorczany","Winona Hoyes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conn-Mann","Ingeborg Rishman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jacobson Inc","Nicholas Commuzzo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dach, Frami and Ferry","Dasya Scales");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Turcotte-Rosenbaum","Hewett Jost");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gleichner, Rutherford and Mann","Jasper Francillo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pacocha, Olson and Vandervort","Deane Braitling");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Breitenberg-Farrell","Sarena Hicken");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tromp Inc","Dillie Besnardeau");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Armstrong, Wuckert and Howe","Raimund Schach");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Robel-Moen","West Stittle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Robel and Sons","Bryce Van Hesteren");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Willms, Skiles and Tremblay","Hermia Spoors");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Smitham and Sons","Valaree Vail");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kessler Group","Latrena Sepey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ferry-Denesik","Stephenie Hernik");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Auer Inc","Barnaby Glauber");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Donnelly, Schaefer and Hoppe","Kelsey Birk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Koch-Howell","Heall Faichnie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johnston-Hirthe","Berkeley Boxen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lehner-Bahringer","Belva Jenyns");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Metz and Sons","Boris Ruthen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weimann, Schaefer and Ziemann","Nadia Tetford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rosenbaum LLC","Mimi Lusted");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bergstrom Inc","Clerissa Readitt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schuster and Sons","Phelia Yurshev");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein, Kreiger and Huels","Thedrick Ancliff");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kirlin-Steuber","Elysia Poser");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cassin-Barrows","Robers Wilmott");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Emmerich, Steuber and Jacobi","Pollyanna Gilkes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wolf-Thompson","Emmet Concannon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Funk, Brown and Williamson","Persis Lanchberry");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ankunding Group","Hynda O'Carney");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Smith LLC","Veriee Bettleson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weimann Inc","Seka Whitehead");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mraz-D'Amore","Nikolaus Colquete");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nikolaus, Quigley and Bashirian","Vernor Scoullar");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gutmann-Ritchie","Vladimir Woodstock");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wilkinson, Balistreri and Gaylord","Celestina Antoshin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wiza, Koelpin and Robel","Dominique Onion");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grimes, Schamberger and Daniel","Montague Widd");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Satterfield, Welch and Dickinson","Rianon Avrahamy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schiller-Pollich","Beverley Denisard");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Adams-Harber","Melisa Spring");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rohan and Sons","Janeta McMurtyr");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pfannerstill LLC","Odelle Leveridge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schinner-Maggio","Jeralee Jacox");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McDermott-Wisoky","Merline Philbrook");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Howell, Abernathy and Ankunding","Carney Huge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Abernathy-Gulgowski","Eadith Burbidge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schaefer LLC","Rickie Lindelof");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Leannon-O'Kon","Linette Le - Count");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Goldner, Buckridge and Schoen","Kamillah Messum");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nikolaus Group","Gena MacParland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gleason-Abbott","Marci Meriot");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lakin, Kub and Mitchell","Rodge Furmedge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lemke Inc","Annalise Benazet");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Abbott-Batz","Marianna Woodsford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hirthe Group","Mignonne Di Giacomo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Feil, Williamson and O'Conner","Betty Sharpin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schinner, Kuhn and Altenwerth","Clementina Medland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Carroll-Watsica","Pauli Trittam");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Franecki Group","Marlene China");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rogahn-Goyette","Ikey Antonsson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kohler, O'Keefe and Simonis","Jobyna McKeggie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kemmer LLC","Veronike Littler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("VonRueden-Ledner","Alexia Duckerin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ullrich-Hane","Leshia Lyburn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Okuneva-Grimes","Marie Serridge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reichel Group","Alfie Mathiasen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Keefe-Batz","Dedra Millichip");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Runolfsdottir, Mertz and Swaniawski","Jenifer Nehlsen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Padberg Group","Pascale Carren");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grimes Inc","Berke Haslock(e)");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hand LLC","Colet Feitosa");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Windler-Ward","Marney Northeast");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Runolfsson-Lakin","Binni Toping");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conroy and Sons","Wendi Northover");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Quitzon, Block and Leffler","Ceil Dowda");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Herzog, Murazik and Thompson","Molly Mailey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lebsack Group","Ephrem Boncoeur");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grimes and Sons","Chane Jose");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johnston Group","Putnem Oakland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Krajcik-Block","Gonzales Symes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hamill-Marks","Felisha Danaher");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heaney LLC","Aida Ling");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schmeler LLC","Yettie Rigglesford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartell, Ledner and Shanahan","Desmond Kyneton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Williamson, Boyle and Jenkins","Laird Siburn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mraz LLC","Johanna Teague");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Blick, Hills and Hilll","Gregorio McPhate");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Blick-Fisher","Burton Moulster");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bednar and Sons","Shayna Surgison");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Smitham, Watsica and Nitzsche","Oralia Bown");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Swaniawski, Mills and Braun","Pammi Durham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Carroll LLC","Binny Maddie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Monahan Inc","Christin Wasbey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beahan LLC","Demetris Mollett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jenkins Group","Ursula Jess");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hagenes-Schiller","Lorry Bonhome");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schmeler LLC","Winona Bellee");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gerlach-Gislason","Maxim Marmion");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kozey and Sons","Fred Fettis");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mitchell-Runte","Arri Moubray");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hermiston-Moore","Adler Darley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fisher-Marquardt","Carmela Parsall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartoletti, Olson and Heller","Micheil Eliot");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fadel Inc","Raddy Swatridge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hartmann, Jenkins and Kuhic","Zelda Pendre");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Doyle Group","Neile Olekhov");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gottlieb Group","Jerrilyn Duprey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Braun and Sons","Gilda Bunford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ritchie, Daugherty and Beer","Quillan Jagels");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gulgowski-Miller","Patti Paunton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Morar-Upton","Nicky Twoohy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein, Prohaska and Gusikowski","Carrie Delagua");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bednar-Romaguera","Yorke Caren");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Simonis Inc","Nananne Varcoe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Russel, Anderson and Kuhlman","Latrena Lequeux");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bode Inc","Carmelia Jansie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("DuBuque-Turner","Ilyssa Mauro");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johnson LLC","Robbi Smallbone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Homenick and Sons","Cathe Pates");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartoletti Group","Kermy Faussett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Luettgen, Anderson and Altenwerth","Hugo Scramage");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kohler, Marks and Herman","Crissy Scrymgeour");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Collier-Bednar","Xena Meekin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jacobi-Weissnat","Amabelle Spier");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Sipes-Medhurst","Jeanine Delhanty");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tillman-Padberg","Kimble Coltman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuhic, Rice and Bednar","Parke Harpham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bailey Group","Celestyna Reimer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Macejkovic-Collins","Tommie Westley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Emard-Nolan","Loella Ashton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Berge-Russel","Arlette Josephy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Turner-O'Connell","Edna O'Lahy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grant-Wisozk","Tedi Kubera");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beahan-Green","Anna Giacomazzo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Thiel-Donnelly","Gardener Cowlas");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reilly, Kub and Wolf","Giles Iacobucci");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Huels and Sons","Barby MacMaykin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schaefer LLC","Mylo Jerams");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bayer-Little","Delores Grcic");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rolfson, Botsford and Schmidt","Jamill Boler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein, Schulist and Ward","Shurlocke Ondracek");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hackett-Marvin","Flin Boyan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Koelpin and Sons","Michail Blair");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Streich, Satterfield and Windler","Frederik Markwelley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Moen, Koss and Spencer","Zora Laite");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Volkman LLC","Serene Pressland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Koch Inc","Selie Fawson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Steuber-Klocko","Amalee Colqueran");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schumm Inc","Willi Cawthorn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dibbert-Halvorson","Doralia Posselt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bernier-Jast","Bert Frise");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McClure Inc","Catina Dymott");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Harris and Sons","Benni Sweatman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schneider, Yost and Weber","Iolande Tevlin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Skiles, Rippin and Medhurst","Nolan Nattriss");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jaskolski, Larson and Heaney","Germaine Hutten");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Olson and Sons","Sabine Yellop");
INSERT INTO `brand` (`name`, `designer`) VALUES ("VonRueden, Greenfelder and Schmidt","Merna Champe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Becker Group","Kenton Robez");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wehner-Larson","Cyrill Work");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Torp LLC","Annalise Pechard");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Metz, Ryan and Kuphal","Therine Halpen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ziemann-Klein","Lennie Horwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marks-Pagac","Jo-ann O'Collopy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fritsch-Kulas","Laird Benitez");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rutherford Group","Annabell Tebbit");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jacobs Group","Lynelle Birtonshaw");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kiehn, Beatty and Turcotte","Stewart Caile");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jenkins, Beatty and Koepp","Patty Ferenc");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lesch-Rutherford","Kevyn Sandercock");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Abbott, Moore and Hane","Daren Pace");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Goyette Group","Ben Philippsohn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Doyle-Casper","Rosella Fantone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hickle-Beier","Gertruda L'Archer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Daniel-Pfeffer","Lazarus Scedall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Effertz-Williamson","Josiah Woodall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weissnat Group","Gipsy Burbridge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Carroll Group","Coop Ridolfi");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kris, Gutkowski and Pacocha","Melisandra Kerss");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heidenreich, Bins and Dare","Hetti Fowells");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stracke-Lakin","Analiese Carrack");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heller-Thompson","Diannne Robel");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rutherford, Gutkowski and Grady","Stormie Gleed");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walter-Harvey","Kata Brinklow");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gorczany, Goyette and Kulas","Roscoe Dudden");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cummerata-Davis","Tiphany Lehrmann");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gusikowski and Sons","Heddie Ridgwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walsh-Dicki","Bartholomew Hacquard");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bauch-Bechtelar","Sanson Lydden");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wolf-Ferry","Phelia Bosse");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Feeney-Jast","Melisenda Chance");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gorczany-Beer","Cliff Gallaher");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Blick and Sons","Elyn Fideler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schowalter Inc","Marian Wroath");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ward LLC","Gilbert Kerkham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ebert LLC","Dorene Mennell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schumm-Huels","Berenice Theobalds");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hackett Inc","Lilias Flory");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Harris-Johnson","Oran Challenor");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bauch-Kilback","Martyn Duffet");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reilly-Berge","Boyce Le land");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dickens Inc","Coretta Elrick");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klocko, Wiegand and Berge","Petronia Webb");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Moore and Sons","Clarita Whitnall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuphal LLC","Karry Solway");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Moen LLC","Holly Gouth");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schuppe-Ruecker","Niall Glynn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lebsack and Sons","Zara Goldthorpe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fritsch and Sons","Bernadine Gawler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pacocha-Corwin","Ad Bolus");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Spencer-Lang","Tessa Cudby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cronin, Nolan and Steuber","Kenyon De la Zenne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beatty, Abshire and Treutel","Linc Beert");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brown Inc","Jonis Boas");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bogisich-Goyette","Maria Bricklebank");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rau-Schuster","Chickie Grouse");
INSERT INTO `brand` (`name`, `designer`) VALUES ("VonRueden and Sons","Gradey Paviour");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Donnelly, Turcotte and Connelly","Toby Chown");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fay, Kertzmann and Breitenberg","Audrie Proudley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pouros and Sons","Kippie Matchell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bins, Kassulke and Haley","Judah Eagleton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Zulauf and Sons","Paulo Schenfisch");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Osinski, DuBuque and Braun","Jenifer Djekovic");
INSERT INTO `brand` (`name`, `designer`) VALUES ("West-Wisoky","Eugen Halson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Effertz, Kunde and Johns","Roxanne Cancellario");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rath-Hirthe","Grace Kemell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bayer, Bernhard and Kunde","Nananne Loudon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conroy Group","Isidore Medwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kris, Parker and Weimann","Jerrilyn Humbert");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cruickshank-Thompson","Betsy Raggles");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cormier Inc","Cori Northedge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cormier, Krajcik and Donnelly","Aubrette Featherston");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Moen, Streich and Bergnaum","Paddy Henlon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wisozk, Koss and Christiansen","Kerr McBayne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Franecki, Waters and D'Amore","Sheelah Aldus");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heidenreich, Schumm and Grimes","Aline Jealous");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Boyle-Gaylord","Deonne Sellack");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gleason-Windler","Rufe Zaniolo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cremin and Sons","Teresina Cator");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Raynor-Trantow","Hatty Kroon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McCullough, Borer and Okuneva","Angelita McGuinness");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mraz Group","Rhona Mulgrew");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bernhard-Stracke","Eleonore Schutte");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Champlin Group","Jedediah Mapledorum");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bosco and Sons","Leona Station");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beer LLC","Domini Minerdo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reichel-Pouros","Ivory Borge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("DuBuque Group","Jennine Boyack");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cassin LLC","Ingemar Boldra");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Thompson Inc","Brand Savin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lakin-Stokes","Bary Cosans");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Sauer, Altenwerth and D'Amore","Marcus Ortner");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walter-Macejkovic","Tye Emerson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Davis and Sons","Georgi La Vigne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Deckow, Smitham and Torphy","Nada O'Skehan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jerde-Paucek","Renado Redler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johns, Gottlieb and Willms","Katheryn Minigo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McDermott Inc","Danna Dimmer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kris Inc","Idaline Napoleone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fisher and Sons","Patricia Dowzell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gulgowski-Stanton","Darryl Prandy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hane, Marks and Haag","Robbin Murkus");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Altenwerth and Sons","Marris Ladloe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Huel, Huel and Paucek","Hermina Kemshell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Connell-Goldner","Granger Thomson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mertz-Lesch","Ricky Pena");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heathcote-Homenick","Silvanus May");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Erdman-Bailey","Lindy Ludgate");
INSERT INTO `brand` (`name`, `designer`) VALUES ("White, Schinner and Denesik","Bevin Toxell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nader Group","Feliza Brantzen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Swaniawski-Hyatt","Arnoldo Thieme");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Balistreri-Jerde","Gordon Lapenna");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Davis, Keeling and Mosciski","Orville Wooder");
INSERT INTO `brand` (`name`, `designer`) VALUES ("West Inc","Cal Finlan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reichert-Schaefer","Harvey Clappson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rau Group","Roxine Ricco");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cummerata LLC","Fredi Dorgon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ortiz, Rice and Ankunding","Julietta Spenton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pfeffer-Ankunding","Edna Dallander");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Prosacco and Sons","Dulcea Wyllcocks");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Paucek-Abbott","Audrye Dumingos");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Little-Osinski","Nada Bontine");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beatty Group","Nadya Wellesley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conroy, Weber and Mertz","Ofelia Shotbolt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cormier and Sons","Elsy Lappine");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Howe-Zieme","Kori Macia");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hickle, Wintheiser and O'Connell","Kelsi Mingo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marvin LLC","Geoffry Klosser");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Veum, Kuhic and Erdman","Malinde Chesher");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wyman Inc","Krista Yurygyn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kautzer-Koss","Arlee Goaks");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Paucek-Bartoletti","Aigneis Tyas");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kirlin Group","Kurtis Reisenstein");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schoen-Harvey","Katina Adams");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stark, Ledner and Renner","Leonore Karpol");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stehr, Moen and Tillman","Grady McAughtrie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brekke-Price","Gil Kime");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kulas, Bruen and Lemke","Zuzana Oldcote");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weber and Sons","Carolyne Crock");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schaefer and Sons","Desmond Quodling");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mueller-Schowalter","Lucine Trassler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ullrich-Shields","Obadias Karchowski");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pacocha, Tillman and Fahey","Georgie Tisun");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lindgren-Orn","Nappy Chimenti");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Keebler, Smitham and Bergstrom","Gabriell Petrolli");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rippin LLC","Reyna Gravener");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McClure and Sons","Boycey Avon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rohan, Lakin and Russel","Rebbecca Crangle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Roob LLC","Berna Iddons");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beier and Sons","Henryetta Choppen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McKenzie-Kautzer","Catharina Trippitt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Spinka-Kihn","Boyce Halford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kunze, Jerde and Pouros","Hugibert Kestian");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cassin-Rogahn","Dulcia Gluyas");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Luettgen, Pfannerstill and Bosco","Iain Hasling");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein LLC","Shari Tiffney");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Goldner Inc","Nanny Ellit");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hettinger, Kerluke and Durgan","Linc Eadmeades");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fahey-Kohler","Daron Schruyers");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gutkowski-Abernathy","Ingelbert Ply");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walter-Kassulke","Paul Hess");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rowe-Green","Aldin Warner");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weimann, Koelpin and Adams","Joyan Dowdam");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stiedemann Group","Reggy Gores");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bradtke-Hintz","Chloris Kelk");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walter-Hand","Mildrid Raxworthy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Balistreri and Sons","Reamonn Jirsa");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Abernathy, Bashirian and Haag","Elisabetta Benitti");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stamm, Spinka and Barrows","Sheela Stanyer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Flatley-Ferry","Joeann Jordi");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Becker Inc","Deborah Ebbens");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bogisich, Stroman and Koelpin","Molli Platts");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schowalter-Bradtke","Raeann Anlay");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Okuneva-Balistreri","Lindsy Tschierasche");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lehner, Heidenreich and Towne","Tyne Gartan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hagenes and Sons","Valina Bilton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Emmerich, Osinski and Daugherty","Maurice Korpolak");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Olson-Ortiz","Xerxes Cheeld");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Senger-Senger","Moshe Wilsdon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cruickshank Group","Frederique Witnall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schuster Group","Sawyere Nurdin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schaden LLC","Alvinia Whillock");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Grimes-Roob","Delia Spelsbury");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Boyle, Goldner and Ortiz","Ransom Drain");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jacobson and Sons","Aubrey Smaridge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Yundt and Sons","Celle Tebboth");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Parker LLC","Merrel Larwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Roob-Larkin","Barbara Bridie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nader, Kihn and Cormier","Padraic Bortolotti");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Glover LLC","Linoel Naptine");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hudson LLC","Corey Jachimiak");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Littel-Vandervort","Daune Bickford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Blanda, Kihn and Crist","Urban Fitzackerley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McCullough-Schultz","Rowland Conant");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Leffler and Sons","Lothaire Cregan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Watsica, Gislason and Hayes","Kirby Salvati");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kozey-Goodwin","Caldwell Oaten");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schamberger, Kutch and King","Pepita Ends");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Feil-Kautzer","Edi Magne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("D'Amore and Sons","Marylee Vennard");
INSERT INTO `brand` (`name`, `designer`) VALUES ("VonRueden, Gleason and Johns","Christel Arrundale");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mayer-Feest","Lonna Cowap");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bashirian, Schmitt and Bednar","Kimberley Galland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Koelpin, Walsh and Bauch","Victoir Harlin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bergstrom-Krajcik","Kliment Vedekhin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lubowitz, Ward and Greenfelder","Adler Porrett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ledner, Lindgren and Schaden","Patin Budleigh");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Larson, Turcotte and Lakin","Demetria Mucklow");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cronin, Braun and Rosenbaum","Christoforo Longmead");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kris, MacGyver and Kunde","Bogey Woan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ritchie Group","Bonita Casazza");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Murray, Tillman and Schoen","Shanta Bollini");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dach Group","Aime Claye");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lehner-Douglas","Nerita Sammons");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Becker LLC","Bobby Rayer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stamm LLC","Kelcie Piddletown");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kautzer Group","Aylmer Baversor");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gleichner, MacGyver and Kreiger","Gayle Mardle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kovacek-Wehner","Kyrstin Axtonne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heidenreich, Baumbach and Osinski","Moreen Syfax");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gusikowski-Lind","Netty Foote");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Renner LLC","Natty Messom");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lemke-Considine","Mair Rennles");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Trantow Group","Anni Persehouse");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conroy, Stiedemann and Rowe","Free Del Castello");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reichert-Rodriguez","Jefferey De Biasio");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Larson-Mitchell","Clarie Osborne");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schumm, Stiedemann and Heller","Alie Bracco");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walker, McCullough and Muller","Susan Colrein");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nader, Olson and Connelly","Carmelita Fulford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mertz, Orn and Jones","Leda Kingzett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reilly-Weissnat","Bernetta Stabbins");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ferry-Braun","Kate McNeilly");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bernier-Grady","Adah Porteous");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lesch-Kassulke","Thomas Stitwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Upton-Waters","Elyn Swetland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Streich, Schowalter and Greenfelder","Les Floyed");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nienow-Kilback","Jolene Juorio");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dietrich-Baumbach","Elfie Butner");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mante-Dibbert","Susi Haggeth");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tromp, O'Kon and Monahan","Vinny Easterfield");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Baumbach LLC","Goran Betteney");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Turner-Morissette","Cello Ellaman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Upton LLC","Cordelie Aldhouse");
INSERT INTO `brand` (`name`, `designer`) VALUES ("MacGyver, Macejkovic and Kirlin","Alana Buxey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Daugherty-Weissnat","Wilek Bold");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jerde Inc","Emanuel Van Velden");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Luettgen LLC","Gardiner Chatburn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kunde-Pagac","Bentley Brennand");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Prosacco-Ritchie","Rodolfo Wadham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fay-Walter","Asa Railton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Casper-Steuber","Shannah Innett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Baumbach, Beahan and Rogahn","Cobbie Dagwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weissnat, Rempel and Mann","Katrine Broadwood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartell-Pfeffer","Crista Ternault");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Yost, Spinka and Moen","Lynn Wyllt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Raynor LLC","Neille Earry");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wiegand-Breitenberg","Carie Crippell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bernhard-Braun","Katheryn Troman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wisoky, Hermann and Hermann","Hattie Franscioni");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reichert-Wisozk","Anastasie Hoggetts");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bode-Wolf","Annecorinne Rodenborch");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Willms-Lemke","Gannie O'Criane");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Franecki, Brekke and Welch","Gaylor Ambrogelli");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kemmer-Smith","Ephrayim Beldham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rau-Vandervort","Cassi Bartolini");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Macejkovic, Luettgen and Gislason","Eryn Eiler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rutherford LLC","Abdul Cruickshanks");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schroeder Inc","Tera Silver");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Smitham-Rosenbaum","Jaquelin Dorricott");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McCullough-Maggio","Iolanthe Daglish");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wisoky, Braun and Nicolas","Antonio Postance");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Walsh Inc","Rosene Haslewood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Collier Inc","Ros Nys");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Franecki, Bernier and Cummerata","Cathrin Mattiessen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Sporer, Dibbert and Will","Kesley Jaffrey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fadel-Hessel","Zed Bradie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wilderman-Marvin","Linda Witheford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Balistreri-Rosenbaum","Radcliffe Collidge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mertz-Harvey","Case Kynastone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jones, Bogisich and Nolan","Bianka Whitwood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dibbert, Pacocha and Kuhlman","Mauricio Newcomb");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ortiz-Funk","Nicki Scurrey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marvin, Morissette and Hessel","Pearce Passfield");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nitzsche, Ondricka and Kirlin","Rena Matteucci");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Smith and Sons","Kerry Billingsly");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dicki Inc","Chas Ingamells");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lemke-Goldner","Amata Urwen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hermann Group","Dania Hearfield");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kshlerin-Bernier","Gerrilee Wilsee");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stracke-Miller","Cameron Priddie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heller LLC","Fulvia Schimank");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ortiz Group","Hannie Kinsman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ruecker-Koelpin","Jeddy Viccars");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Little LLC","Drona Legendre");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Von LLC","Kiley Hamments");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Powlowski LLC","Marget Coult");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Eichmann LLC","Portie Shackesby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartoletti-Fisher","Coletta Keates");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schamberger-Weissnat","Hilliary Stronge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rau Inc","Gillan Manuele");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dickinson-Kunde","Hilario Ivashin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Green Inc","Cecily Reyna");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Corwin, Carter and Treutel","Karina Allwood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beier and Sons","Tanitansy Haws");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pollich, Hansen and Pacocha","Henderson Smitheram");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mraz-Fritsch","Ban Titchener");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cormier, Gottlieb and Dibbert","Park Dobbson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Prosacco-Sauer","Myrwyn Curness");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Willms LLC","Raddy Haysey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brakus-Abbott","Bartholomew Daens");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kub Inc","Jolyn Van Halle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kunze-Green","Nonah McLellan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hirthe-Doyle","Dukey Aspy");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Maggio, Hirthe and Schneider","Latrena Toffano");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Botsford, Little and Maggio","Algernon Livzey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jacobson, Crona and Leannon","Selestina Burkitt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cormier Group","Fair Brownsett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gutmann Inc","Adelheid Kevis");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bergnaum-Lemke","Silvester Baribal");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Aufderhar, Rohan and Maggio","Dianne Kliement");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gleichner-Swift","Rosanna Fibbit");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Keebler LLC","Sara Fullager");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Denesik-Rodriguez","Nadiya Schistl");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lebsack Inc","Spencer Kleanthous");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Okuneva-Feeney","Dana McCarly");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Shanahan-Grant","Katrinka Rubinowitz");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Luettgen-Schiller","Elladine Wards");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hane, Jacobson and Hoeger","Amory Node");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Connell LLC","Shirlee Betke");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dooley-Ullrich","Kaine Jaher");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Conn Group","Kynthia Kirkbride");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Friesen LLC","Adele Spurnier");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stracke, Kris and Blick","Flossi Matveiko");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nitzsche, Gleichner and Streich","Dev Jouanny");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuphal, Champlin and Sanford","Sonny Chin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Waters Inc","Jasmina Canada");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nolan LLC","Tiebold Hoyes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ondricka-Davis","Agretha Domone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Yundt, Durgan and Brown","Bianca Reddin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Keefe LLC","Adelaida Domotor");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beahan Group","Riane Downs");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein, Rau and Casper","Kym Cosley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reynolds-MacGyver","Julie Pashba");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mann, Altenwerth and Krajcik","Yetta O' Meara");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kulas, Stracke and Turcotte","Sarah Dalgardno");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Littel, Lakin and Hauck","Claribel Mallebone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bogisich, Ratke and Robel","Nettie Bridgement");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beier, Klocko and Witting","Sheelah Whiteside");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hansen-Rowe","Marylee Eynon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kutch-Farrell","Brett Andreuzzi");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stamm-Schuppe","Prentiss Cunrado");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nader, Shanahan and Abbott","Carmela Lumby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Abernathy-Lindgren","Ingelbert Hardwicke");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Aufderhar-Grady","Tiphanie Tommasuzzi");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Yost LLC","Perice Koppen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Osinski-Treutel","Temple Fordyce");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kuphal-Prohaska","Tyler Rowley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Labadie-Torp","Georgianne Roly");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Murazik, Borer and Kuhlman","Kleon Labram");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johnston Inc","Eada Dodding");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Volkman Inc","Clio Crush");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dickens-Block","Arlee Currm");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Swift-Kessler","Sherill Edgerton");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fisher-Abernathy","Arabela Causley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Connelly, Windler and Kertzmann","Leslie Honnicott");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Swift-Lemke","Darelle Menendez");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schamberger-Mayert","Caria Houseago");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kautzer-Rosenbaum","Berty Toffaloni");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Roob, Bergnaum and Kunde","Jennie Golsthorp");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cummerata and Sons","Wadsworth Dani");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jenkins, Greenholt and Jacobson","Stacy Mandrake");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Davis-Sipes","Jared McCullen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mueller LLC","Lianna Foxley");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McCullough Group","Ravid Howland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Homenick LLC","Jackquelin Longwood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jones, Paucek and Senger","Nikos Branwhite");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Connell-Jenkins","Loreen Carwithan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Romaguera LLC","Worden De Filippo");
INSERT INTO `brand` (`name`, `designer`) VALUES ("VonRueden, Fisher and Homenick","Liliane Otterwell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Marks-Doyle","Ive Stoker");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bruen-Shields","Carlene Delong");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Block LLC","L;urette Probyn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cassin-Leuschke","Sid Crothers");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Brekke, Lesch and Hilpert","Dulce Towse");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Greenholt, Cormier and Mante","Delly Spriddle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schamberger Inc","Karon Learmond");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kreiger Group","Westbrook Dobbie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Green Group","Sharla Franceschino");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schumm, Hermiston and Ratke","Hagan Keppie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Little Group","Lotte Miskimmon");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Johns, Dibbert and Senger","Griffith Kausche");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jakubowski LLC","Bennett Blomefield");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mante-Hermann","Joscelin Whetnall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schmeler-Wuckert","Shawnee Adamolli");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cummings LLC","Reina Munslow");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Daugherty, Nolan and Weissnat","Marita Landsman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Oberbrunner, Goyette and Runolfsdottir","Nina Sheilds");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hansen and Sons","Pren Mulberry");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartell-Hickle","Ganny Creagh");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Willms Group","Lil Le Monnier");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Batz and Sons","Fergus Roj");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Legros-Carter","Brunhilda Fitch");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Emard-Schuster","Jerald Elt");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Zboncak, Champlin and Heller","Quillan Hodgets");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Swift-Mante","Kirby Thuillier");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lowe-Ondricka","Gordy Mitie");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Turcotte-Botsford","Morgen Ottery");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rau Group","Lucien Henighan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heidenreich, Collier and Hane","Phylis Acres");
INSERT INTO `brand` (`name`, `designer`) VALUES ("King, Heaney and Auer","Wyatan Summerly");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bergnaum, Weimann and Bosco","Gib Fishburn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tromp-Haley","Garrett Bolingbroke");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gutmann-Mayer","Ainslie Silson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rodriguez, Crooks and Nikolaus","Brantley Oakenford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hodkiewicz, Bahringer and Jenkins","Miguel Charity");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Herzog, Cremin and Block","Ollie Kirkup");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bode-Streich","Earvin Gianni");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kemmer LLC","Dedie Cudiff");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Murray, Stroman and Funk","Lonnie Oppery");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mosciski-Swift","Artemus Bazek");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Murazik, Witting and Gleichner","Malinde Brainsby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Howell, Jakubowski and Gutkowski","Bonni Ysson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McDermott-Medhurst","Astrid Gerardeaux");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cremin, Kuhlman and Murphy","Scarface Fawkes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Smith-Hirthe","Duke Froment");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Robel, Yundt and Walker","Bev Woollons");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dach, Boehm and Lindgren","Garvin Rickaby");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Stracke, Mayert and Pagac","Xylia Greensted");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hermiston-Stamm","Dulcinea Freear");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Anderson, Boyer and Littel","Kalvin Caldera");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Robel and Sons","Catlee Aslen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Baumbach LLC","Niven Carlone");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Gottlieb and Sons","Taffy Greim");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Koepp-Lowe","Deane Clipsham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Botsford Inc","Karlis Greenhaugh");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tillman Group","Curtice Jouanot");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Schmeler, Bartoletti and Hermann","Bram Blabey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Altenwerth, Witting and Wolff","Clarissa Wheeler");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Thompson-Gaylord","Aubrette Ormonde");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Aufderhar LLC","Gianna Sapey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Franecki-Olson","Golda Earey");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hegmann LLC","Shelley Barhem");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Leuschke, Beatty and Wolf","Randolph Jervis");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kling-Schroeder","Ram Itzakson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bayer-Yundt","Dee dee Wessing");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Reichert, Jast and Bailey","Corrinne St. Aubyn");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Crist-Ferry","Caria Poyner");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wiegand, Torp and Lowe","Joana Priestland");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Goyette, Gulgowski and Senger","Iormina Kenninghan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kertzmann, Smith and Willms","Gregorio Filippov");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lesch-Brakus","Sara-ann Karchewski");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jakubowski Inc","Celka Rosentholer");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kassulke-Gaylord","Franklyn Molden");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Heller LLC","Efrem Battman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("West-Mitchell","Christy Sandes");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nitzsche, Metz and Quitzon","Micah Redgewell");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Beahan LLC","Aurthur Parlett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("McClure, Harvey and Littel","Anneliese Cockayme");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Herman, Rau and O'Conner","Ingrim Stinson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Medhurst Inc","Debi O'Connor");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Friesen-Lesch","Claudine Stolberger");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rodriguez, Hagenes and Mohr","Anet Hartegan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Roob-Cummerata","Asher Petrelli");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bauch Group","Ashley Acarson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Greenholt-Jakubowski","Filberte Gally");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Farrell, Bednar and Abernathy","Herbie Strangeway");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Nitzsche, Bartoletti and Padberg","Leoine Mertgen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Blanda Inc","Jean Athowe");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bednar, Durgan and Hettinger","Terry Loder");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Klein, Wunsch and Smith","Griselda Wiersma");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kovacek Group","Cornelius Agerskow");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Wehner, Welch and Rutherford","Viva Usherwood");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Ortiz, Legros and Cole","Mile Gimenez");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Jacobi-Okuneva","Prinz Lightman");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Pfeffer, Mueller and Eichmann","Zora Harford");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Anderson, Rippin and Lesch","Vivyanne Stobbart");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lueilwitz, Sporer and Breitenberg","Bonnie Milesap");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bailey-Lowe","Addi Bridge");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Weimann LLC","Elwira Mabson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hayes-Boyer","Sandye Jouanot");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Veum, Harber and Satterfield","Guthrie Leggan");
INSERT INTO `brand` (`name`, `designer`) VALUES ("O'Conner LLC","Buckie Esselin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Romaguera-Von","Connie Warmisham");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Lebsack, Gottlieb and Huels","Lou Gannicleff");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Homenick, O'Hara and Hahn","Meridith Niezen");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Cartwright, Schaden and Fay","Rory Eckert");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hirthe Inc","Barron Lupson");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bartell Inc","Joelynn Rawle");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Dare, Kessler and Moore","Jacklyn Malter");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Fahey-Hilpert","Starla Barlthrop");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Bailey-Prosacco","Hilliary Rossi");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Treutel LLC","Brockie Hassett");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Yost LLC","Matt Gurrado");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tromp LLC","Nicolina Fullerlove");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Langosh LLC","Zarla Brazier");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Mante, Daniel and Cummings","Lorilee Davenall");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Kozey, Bahringer and Prohaska","Rustin Kaines");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rippin-Mertz","Napoleon Andreix");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Romaguera, Beer and Cormier","Brianna Cantos");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Tremblay, Herman and Stamm","Baudoin Von Welldun");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Rowe, Rowe and Rutherford","Lazare Lindback");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Harris-McGlynn","Jena Bohin");
INSERT INTO `brand` (`name`, `designer`) VALUES ("Hirthe, Halvorson and Feeney","Nedda Bartosik");