INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (1,"clothing",null);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (2,"shirt",1);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (3,"pant",1);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (4,"shorts",1);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (5,"socks",1);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (6,"underwear",1);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (7,"sweatshirt",1);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (8,"swimwear",1);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (9,"tee",2);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (10,"long sleeve",2);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (11,"polo",2);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (12,"dress",2);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (13,"tank top",2);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (14,"athletic",2);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (15,"denim",3);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (16,"khaki",3);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (17,"chino",3);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (18,"cargo",3);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (19,"corduroy",3);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (20,"sweatpants",3);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (21,"denim",4);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (22,"pleated",4);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (23,"cargo",4);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (24,"athletic",4);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (25,"long",5);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (26,"short",5);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (27,"thigh high",25);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (28,"knee high",25);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (29,"calf high",25);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (30,"Mid-calf high",25);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (31,"crew",25);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (32,"quarter",26);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (33,"no show",26);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (34,"slip-on padding",26);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (35,"brief",6);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (36,"boxer",6);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (37,"boxer brief",6);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (38,"panty",6);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (39,"boy short",6);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (40,"hoodie",7);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (41,"pullover",7);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (42,"crop top",7);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (43,"off shoulder",7);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (44,"trunk",8);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (45,"bikini",8);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (46,"one piece",8);
INSERT INTO `product_type` (`id`, `name`, `parent_id`) VALUES (47,"three piece",8);