INSERT INTO vendor (name, email) VALUES ('Reichert and Sons', 'vstopford0@biblegateway.com');
INSERT INTO vendor (name, email) VALUES ('Jones Group', 'hhow1@sogou.com');
INSERT INTO vendor (name, email) VALUES ('Gleichner and Sons', 'pgourley2@bloomberg.com');
INSERT INTO vendor (name, email) VALUES ('Rowe-Emard', 'jdoak3@washington.edu');
INSERT INTO vendor (name, email) VALUES ('Bailey, Hand and McKenzie', 'bbeggio4@technorati.com');
INSERT INTO vendor (name, email) VALUES ('Stroman-Cassin', 'bspratling5@wiley.com');
INSERT INTO vendor (name, email) VALUES ('Cremin, Jenkins and Hane', 'sburner6@mail.ru');
INSERT INTO vendor (name, email) VALUES ('Zboncak-Padberg', 'qgossling7@sohu.com');
INSERT INTO vendor (name, email) VALUES ('Flatley, Walsh and Hickle', 'sleynham8@devhub.com');
INSERT INTO vendor (name, email) VALUES ('Vandervort LLC', 'megdal9@mayoclinic.com');
INSERT INTO vendor (name, email) VALUES ('Frami-Frami', 'hwilliamsona@chron.com');